### ISSUE TITLE
Add lattice to active profiles if running in lattice

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-lattice#3]
@mstine do you think this is worth it, or just let the user add an environment variable?

**Comment by dsyer** [comment]
I think it's worth it, if there's a reliable way to detect that we are running in lattice (as opposed to generaically diego).

**Comment by spencergibb** [comment]
We are currently doing this in [LatticeCloudApplicationListener](https://github.com/spring-cloud/spring-cloud-lattice/blob/master/spring-cloud-lattice-core/src/main/java/org/springframework/cloud/lattice/LatticeCloudApplicationListener.java#L31-L34). If I'm not mistaken, `PROCESS_GUID` is added by the lattice cli.
