### ISSUE TITLE
rename to spring-cloud-diego

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-lattice#5]
Since diego is what we are really targeting here.

**Comment by dsyer** [comment]
spring-cloud-receptor?

**Comment by spencergibb** [comment]
If we rename, would we rename the [activated profile](https://github.com/spring-cloud/spring-cloud-lattice/blob/master/spring-cloud-lattice-core/src/main/java/org/springframework/cloud/lattice/LatticeCloudApplicationListener.java#L33) too?

**Comment by dsyer** [comment]
I guess (cc @markfisher). Maybe "lattice" isn't such a dumb name for most apps.

**Comment by markfisher** [comment]
I don't quite understand the rationale for a name change. Diego will be the underlying runtime for Cloud Foundry itself, and yet this project should not be used for Cloud Foundry apps. For one thing, AFAIK the Receptor API would not even be exposed but used internally behind the Cloud Controller API. This project is only useful for the case where there is no first-class concept of bound services, and currently that just means Lattice.

**Comment by spencergibb** [comment]
I think there we concerns early on that this might be useful in more than one context.  If not, we can close the issue.
