### ISSUE TITLE
Change version to 1.0.0

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-lattice#8]
We haven't had a 1.0.0 so 1.1.0 is wrong.

**Comment by markfisher** [comment]
IMO it's too late to make this change since 1.1.0 has already been used. Otherwise it will create confusion when you do make it to 1.1.0.

**Comment by spencergibb** [comment]
It has never been released except for snapshots.

**Comment by markfisher** [comment]
artfiacts exist in public, snapshot or not, that in my book is a release :)

**Comment by dsyer** [comment]
Snapshots don't count IMO. When we move to 1.1.0 for real the timestamps will override anything so far deployed.

**Comment by markfisher** [comment]
okay
